### ISSUE TITLE
Project Files Already Completed

### ISSUE THREAD

**Issue by joshpcausey** [onehungrymind/fem-enterprise-patterns#2]
I'm going through this course on frontendmasters.com. I'm a few hours in and I've realized that all of the solutions to the problems are already filled in. For example, when looking at the home component for the micro solution you'll notice the challenge is already complete.

Is this by design or should this be corrected?

**Comment by belev** [comment]
I just noticed the same thing when I got to the first exercise. IMO it would be nice to have it separated 😊.

**Comment by joshpcausey** [comment]
Hey @jdgarvey do you have any info on this? I think there will be more people with the same issue coming as more people start taking this course. I also imagine a lot of people could drop out pretty early due to the confusion.

**Comment by joshpcausey** [comment]
Hey @simpulton and @jdgarvey. Thank you updating 2 of the project files and adding a start branch. Is there any way we could get the uncompleted files for the other 6?

**Comment by joshpcausey** [comment]
Thank you for making some changes a few days ago @simpulton and @jdgarvey. Just from a first look on the start branch, the meso project is still a complete solution where it should be an incomplete solution. This has made taking your course extremely difficult. I really hope we can work together and get this fixed.

**Comment by simpulton** [comment]
My apologies - I thought I pushed up the meso change. It should be fixed now.
